export const SURAH_ID_TRANSLATION: Record<number, string> = {
  1: "Pembukaan",
  2: "Sapi Betina",
  3: "Keluarga 'Imran",
  4: "Wanita",
  5: "Jamuan (hidangan makanan)",
  6: "Binatang Ternak",
  7: "Tempat yang tertinggi",
  8: "Harta rampasan perang",
  9: "Pengampunan",
  10: "Nabi Yunus",
  11: "Nabi Hud",
  12: "Nabi Yusuf",
  13: "Guruh (petir)",
  14: "Nabi Ibrahim",
  15: "Al Hijr (nama gunung)",
  16: "Lebah",
  17: "Perjalanan Malam",
  18: "Penghuni-penghuni gua",
  19: "Maryam (Maria)",
  20: "Ta Ha",
  21: "Nabi-Nabi",
  22: "Haji",
  23: "Orang-orang mukmin",
  24: "Cahaya",
  25: "Pembeda",
  26: "Penyair",
  27: "Semut",
  28: "Cerita",
  29: "Laba-laba",
  30: "Bangsa Romawi",
  31: "Keluarga Luqman",
  32: "Sajdah",
  33: "Golongan-golongan yang bersekutu",
  34: "Kaum Saba'",
  35: "Pencipta",
  36: "Ya Sin",
  37: "Barisan-barisan",
  38: "Shaad",
  39: "Rombongan-rombongan",
  40: "Orang yg Beriman",
  41: "Yang dijelaskan",
  42: "Musyawarah",
  43: "Perhiasan",
  44: "Kabut",
  45: "Yang berlutut",
  46: "Bukit-bukit pasir",
  47: "Nabi Muhammad",
  48: "Kemenangan",
  49: "Kamar-kamar",
  50: "Qaaf",
  51: "Angin yang menerbangkan",
  52: "Bukit",
  53: "Bintang",
  54: "Bulan",
  55: "Yang Maha Pemurah",
  56: "Hari Kiamat",
  57: "Besi",
  58: "Wanita yang mengajukan gugatan",
  59: "Pengusiran",
  60: "Wanita yang diuji",
  61: "Satu barisan",
  62: "Hari Jum'at",
  63: "Orang-orang yang munafik",
  64: "Hari ditampakkan kesalahan-kesalahan",
  65: "Talak",
  66: "Mengharamkan",
  67: "Kerajaan",
  68: "Pena",
  69: "Hari Kiamat",
  70: "Tempat naik",
  71: "Nabi Nuh",
  72: "Jin",
  73: "Orang yang berselimut",
  74: "Orang yang berkemul",
  75: "Hari Kiamat",
  76: "Manusia",
  77: "Malaikat-Malaikat Yang Diutus",
  78: "Berita besar",
  79: "Malaikat-Malaikat Yang Mencabut",
  80: "Ia Bermuka masam",
  81: "Menggulung",
  82: "Terbelah",
  83: "Orang-orang yang curang",
  84: "Terbelah",
  85: "Gugusan bintang",
  86: "Yang datang di malam hari",
  87: "Yang paling tinggi",
  88: "Hari Pembalasan",
  89: "Fajar",
  90: "Negeri",
  91: "Matahari",
  92: "Malam",
  93: "Waktu matahari sepenggalahan naik",
  94: "Melapangkan",
  95: "Buah Tin",
  96: "Segumpal Darah",
  97: "Kemuliaan",
  98: "Pembuktian",
  99: "Kegoncangan",
  100: "Berlari kencang",
  101: "Hari Kiamat",
  102: "Bermegah-megahan",
  103: "Masa/Waktu",
  104: "Pengumpat",
  105: "Gajah",
  106: "Suku Quraisy",
  107: "Barang-barang yang berguna",
  108: "Nikmat yang berlimpah",
  109: "Orang-orang kafir",
  110: "Pertolongan",
  111: "Gejolak Api / Sabut",
  112: "Memurnikan Keesaan Allah",
  113: "Waktu Subuh",
  114: "Umat Manusia"
};
