import type { Dua } from "@/features/quran/types";

export const DUAS: Dua[] = [
  {
    id: 1,
    title: "Dua Before Eating",
    titleId: "Doa Sebelum Makan",
    arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ",
    latin: "Bismillāhi wa 'alā barakatillāh",
    translationId: "Dengan nama Allah dan atas berkah Allah.",
    translationEn: "In the name of Allah and with the blessings of Allah.",
    source: "Abu Dawud 3767",
  },
  {
    id: 2,
    title: "Dua After Eating",
    titleId: "Doa Sesudah Makan",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مِنَ الْمُسْلِمِينَ",
    latin: "Alḥamdulillāhil-ladhī aṭ'amanā wa saqānā wa ja'alanā minal-muslimīn",
    translationId: "Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami termasuk golongan orang-orang muslim.",
    translationEn: "All praise is for Allah who fed us, gave us drink, and made us Muslims.",
    source: "Abu Dawud 3850",
  },
  {
    id: 3,
    title: "Dua Before Sleeping",
    titleId: "Doa Sebelum Tidur",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    latin: "Bismikallāhumma amūtu wa aḥyā",
    translationId: "Dengan nama-Mu ya Allah, aku mati dan aku hidup.",
    translationEn: "In Your name O Allah, I die and I live.",
    source: "Bukhari 6324",
  },
  {
    id: 4,
    title: "Dua After Waking Up",
    titleId: "Doa Bangun Tidur",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    latin: "Alḥamdulillāhil-ladhī aḥyānā ba'da mā amātanā wa ilayhin-nushūr",
    translationId: "Segala puji bagi Allah yang telah menghidupkan kami setelah mematikan kami, dan kepada-Nya lah tempat kembali.",
    translationEn: "All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.",
    source: "Bukhari 6312",
  },
  {
    id: 5,
    title: "Dua Entering the Mosque",
    titleId: "Doa Masuk Masjid",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    latin: "Allāhummaf-taḥ lī abwāba raḥmatik",
    translationId: "Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.",
    translationEn: "O Allah, open for me the doors of Your mercy.",
    source: "Muslim 713",
  },
  {
    id: 6,
    title: "Dua Leaving the Mosque",
    titleId: "Doa Keluar Masjid",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    latin: "Allāhumma innī as'aluka min faḍlik",
    translationId: "Ya Allah, sesungguhnya aku memohon karunia-Mu.",
    translationEn: "O Allah, I ask You of Your bounty.",
    source: "Muslim 713",
  },
  {
    id: 7,
    title: "Dua for Travel",
    titleId: "Doa Bepergian",
    arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى",
    latin: "Allāhumma innā nas'aluka fī safarinā hadhal-birra wat-taqwā",
    translationId: "Ya Allah, sesungguhnya kami memohon kepada-Mu dalam perjalanan ini kebaikan dan ketakwaan.",
    translationEn: "O Allah, we ask You on this journey for righteousness and piety.",
    source: "Muslim 1342",
  },
  {
    id: 8,
    title: "Dua for Anxiety and Sorrow",
    titleId: "Doa Menghilangkan Kesedihan",
    arabic: "اللَّهُمَّ إِنِّي عَبْدُكَ وَابْنُ عَبْدِكَ وَابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ",
    latin: "Allāhumma innī 'abduka wabnu 'abdika wabnu amatika nāṣiyatī biyadik",
    translationId: "Ya Allah, sesungguhnya aku adalah hamba-Mu, anak hamba-Mu, dan ubun-ubunku ada di tangan-Mu.",
    translationEn: "O Allah, I am Your servant, son of Your servant, son of Your maidservant; my forelock is in Your hand.",
    source: "Ahmad 3704",
  },
  {
    id: 9,
    title: "Dua for Forgiveness",
    titleId: "Doa Memohon Ampunan",
    arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
    latin: "Allāhumma innaka 'afuwwun tuḥibbul-'afwa fa'fu 'annī",
    translationId: "Ya Allah, sesungguhnya Engkau Maha Pemaaf, Engkau menyukai maaf, maka maafkanlah aku.",
    translationEn: "O Allah, indeed You are Pardoning; You love pardon, so pardon me.",
    source: "Tirmidhi 3513",
  },
  {
    id: 10,
    title: "Dua for Protection",
    titleId: "Doa Perlindungan",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    latin: "A'ūdhu bikalimātillāhit-tāmmāti min sharri mā khalaq",
    translationId: "Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk-Nya.",
    translationEn: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    source: "Muslim 2708",
  },
  {
    id: 11,
    title: "Dua After Adhan",
    titleId: "Doa Sesudah Adzan",
    arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلاَةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ",
    latin: "Allāhumma rabba hādhihid-da'watit-tāmmati waṣ-ṣalātil-qā'imati āti muḥammadanil-wasīlah",
    translationId: "Ya Allah, Tuhan pemilik seruan yang sempurna ini dan sholat yang akan ditegakkan, berikanlah wasilah kepada Muhammad.",
    translationEn: "O Allah, Lord of this perfect call and the prayer to be offered, grant Muhammad the wasilah.",
    source: "Bukhari 614",
  },
  {
    id: 12,
    title: "Dua in the Morning (Sayyidul Istighfar)",
    titleId: "Sayyidul Istighfar (Pagi)",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    latin: "Allāhumma anta rabbī lā ilāha illā anta khalaqtanī wa anā 'abduk",
    translationId: "Ya Allah, Engkau adalah Rabb-ku. Tidak ada ilah yang berhak disembah kecuali Engkau. Engkau yang menciptakanku dan aku adalah hamba-Mu.",
    translationEn: "O Allah, You are my Lord; there is no god worthy of worship except You. You created me and I am Your servant.",
    source: "Bukhari 6306",
  },
  {
    id: 13,
    title: "Dua for Parents",
    titleId: "Doa untuk Orang Tua",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    latin: "Rabbir-ḥamhumā kamā rabbayānī ṣaghīrā",
    translationId: "Ya Rabb-ku, sayangilah keduanya (kedua orang tuaku) sebagaimana mereka mendidikku sewaktu kecil.",
    translationEn: "My Lord, have mercy upon them as they brought me up when I was small.",
    source: "Quran 17:24",
  },
  {
    id: 14,
    title: "Dua for Guidance",
    titleId: "Doa Memohon Hidayah",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا",
    latin: "Rabbanā lā tuzigh qulūbanā ba'da idh hadaytanā",
    translationId: "Ya Tuhan kami, janganlah Engkau palingkan hati-hati kami setelah Engkau memberi petunjuk kepada kami.",
    translationEn: "Our Lord, do not let our hearts deviate after You have guided us.",
    source: "Quran 3:8",
  },
  {
    id: 15,
    title: "Dua for Good in This World and Hereafter",
    titleId: "Doa Kebaikan Dunia & Akhirat",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    latin: "Rabbanā ātinā fid-dunyā ḥasanatan wa fil-ākhirati ḥasanatan wa qinā 'adhāban-nār",
    translationId: "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari siksa neraka.",
    translationEn: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the torment of the Fire.",
    source: "Quran 2:201",
  },
  {
    id: 16,
    title: "Dua When Entering Home",
    titleId: "Doa Masuk Rumah",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ",
    latin: "Allāhumma innī as'aluka khayral-mawlaji wa khayral-makhraj",
    translationId: "Ya Allah, sesungguhnya aku memohon kepada-Mu kebaikan masuk dan kebaikan keluar.",
    translationEn: "O Allah, I ask You for the good of entering and the good of leaving.",
    source: "Abu Dawud 5095",
  },
  {
    id: 17,
    title: "Dua Against Debt",
    titleId: "Doa Melunasi Hutang",
    arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    latin: "Allāhummak-finī biḥalālika 'an ḥarāmika wa aghnini bifaḍlika 'amman siwāk",
    translationId: "Ya Allah, cukupkanlah aku dengan yang halal-Mu sehingga aku tidak perlu kepada yang haram-Mu, dan kayakanlah aku dengan karunia-Mu sehingga aku tidak perlu kepada selain-Mu.",
    translationEn: "O Allah, suffice me with what is lawful against what is unlawful, and enrich me by Your grace to need none other than You.",
    source: "Tirmidhi 3563",
  },
  {
    id: 18,
    title: "Istigfar (Seeking Forgiveness)",
    titleId: "Istighfar",
    arabic: "أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
    latin: "Astaghfirullāhal-'aẓīmal-ladhī lā ilāha illā huwal-ḥayyul-qayyūmu wa atūbu ilayh",
    translationId: "Aku memohon ampun kepada Allah Yang Maha Agung, yang tidak ada Tuhan selain Dia, Yang Maha Hidup, Yang Berdiri Sendiri, dan aku bertobat kepada-Nya.",
    translationEn: "I seek forgiveness from Allah, the Magnificent, besides Whom there is no deity, the Ever-Living, the Self-Sustaining, and I repent to Him.",
    source: "Abu Dawud 1517",
  },
  {
    id: 19,
    title: "Dua When Seeing the Moon",
    titleId: "Doa Melihat Bulan",
    arabic: "اللَّهُ أَكْبَرُ اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْأَمْنِ وَالْإِيمَانِ",
    latin: "Allāhu akbar, Allāhumma ahillahu 'alaynā bil-amni wal-īmān",
    translationId: "Allah Maha Besar. Ya Allah, tampakkan ia kepada kami dengan keamanan dan keimanan.",
    translationEn: "Allah is the Greatest. O Allah, let this moon appear on us with security and faith.",
    source: "Tirmidhi 3451",
  },
  {
    id: 20,
    title: "Dua for Rain",
    titleId: "Doa Minta Hujan",
    arabic: "اللَّهُمَّ أَغِثْنَا اللَّهُمَّ أَغِثْنَا اللَّهُمَّ أَغِثْنَا",
    latin: "Allāhumma aghithnā, Allāhumma aghithnā, Allāhumma aghithnā",
    translationId: "Ya Allah tolonglah kami. Ya Allah tolonglah kami. Ya Allah tolonglah kami.",
    translationEn: "O Allah, send us rain! O Allah, send us rain! O Allah, send us rain!",
    source: "Bukhari 1014",
  },
];
